<?php
$url = env('PAYPAL_MARKETPLACE_SANDBOX') && env('API_TEST_REDIRECT_URL') ?
    env('API_TEST_REDIRECT_URL') : env('APP_URL');

return [

    /**
     * API credentials
     */
    'api' => [
        'client_id' => env('PAYPAL_MARKETPLACE_CLIENT_ID'),
        'secret' => env('PAYPAL_MARKETPLACE_SECRET'),
        'sandbox' => env('PAYPAL_MARKETPLACE_SANDBOX'),
    ],

    /**
     * visit: https://www.paypal.com/businessmanage/account/aboutBusiness
     */
    'partner_merchant_id' => env('PAYPAL_MARKETPLACE_MERCHANT_ID'),

    /**
     * Partner redirect url after onboarding
     */
    'partner_redirect_url' => $url . '/admin/setting/paypalMarketplace/redirect',

    /**
     * Webhook Id as generated by artisan command "paypal:configure-webhook"
     * Or get it from developer dashboard under webhooks.
     */
    'webhook_id' => env('PAYPAL_MARKETPLACE_WEBHOOK_ID'),
];
